[build]
builder = "nixpacks"

[build.nixpacks]
provider = "nodejs"

[deploy]
startCommand = "npm run start"
buildCommand = "npm run install-backend"

[environments.production]
variables = [
  { name = "NODE_ENV", value = "production" },
  { name = "JWT_SECRET", generateValue = true }
]