[build]
builder = "nixpacks"

[build.nixpacks]
provider = "nodejs"

[deploy]
startCommand = "cd backend && npm install && npm run start"
buildCommand = "cd backend && npm install"

[environments.production]
variables = [
  { name = "NODE_ENV", value = "production" },
  { name = "JWT_SECRET", generateValue = true }
]